# WSA Numpy Demo

### Imports
- If not already installed, don't forget to run `pip install numpy` in your terminal first!  
- If that doesn't work, try `conda install numpy` instead.

In [1]:
# Make sure to run this cell!
import numpy as np

### Creating Numpy Arrays

* NumPy arrays can be 1-dimensional, 2-dimensional (like a matrix), and so forth.   
* Each dimension is called an axis, and the `shape` property describes the array's size along each axis.  
* `a` only has 1 axis, and `b` and `c` have 2 axes.

In [3]:
# Creating NumPy array from python list using np.array() function
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [5]:
# These can be multiple dimensions -- just use nested lists!
b = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])  # 2x3 array
print(b)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [7]:
c = np.array([[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]])  # 3x2 array
print(c)

[[1.1 2.2]
 [3.3 4.4]
 [5.5 6.6]]


In [9]:
print([a.shape, b.shape, c.shape])
print([a.dtype, b.dtype, c.dtype])

[(6,), (2, 3), (3, 2)]
[dtype('int32'), dtype('float64'), dtype('float64')]


### Setting Values w/ Functions
* `np.arange()`
* `np.linspace()`
* `np.empty()`
* `np.full()`
* `np.zeros()`
* `np.ones()`

In [11]:
# Instantiate a 1D array containing every value in a specified range with np.arange(end_value)
# Here, array d contains every whole number up to 5
d = np.arange(5)
print(d)

[0 1 2 3 4]


In [13]:
# np.arange(start_value, end_value, step_size)
e = np.arange(2, 5, 0.1)
print(e)

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7
 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


In [15]:
# If we want to use decimals but don't know the step size, it won't work as intended
f = np.arange(2, 5.1)
print(f)

[2. 3. 4. 5.]


In [17]:
# Using np.linspace(start_value, end_value, num_elem), data is evenly separated
g = np.linspace(2, 5, 50)
print(g)

[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]


In [19]:
# Instantiate an empty array with a specified shape, in this case (2,3)
# The array is not truly "empty" - it just contains uninitialized values!
h = np.empty((2,3))
print(h)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [21]:
# Instantiate an array with a specified shape, and fill every cell with a specified value
# Here, array i is a 2x3 array filled with 7s
i = np.full((2,3), 7)
print(i)

[[7 7 7]
 [7 7 7]]


In [23]:
# Similar to np.full, np.zeros creates an array filled with 0s
j = np.zeros((2,3))
print(j)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# np.ones creates an array filled with 1s
k = np.ones((2,3))
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]


### Slicing and Indexing Arrays

In [27]:
# We can index like a python list... gives us data at index 0
print(a[0])

1


In [29]:
# We can also get sub-arrays ... gives us data from index 2 inclusive to the end
print(a[2:])  # type is still an array

[3 4 5 6]


In [31]:
# You can pass a list (or a NumPy array) as the index to get data from multiple indices
print(a[[1,3,5]])  # gives us data from index 1, 3, and 5

[2 4 6]


In [33]:
# index 0 of axis 0 gives us the first row: [1.1, 2.2, 3.3].
print(b[0])
print(b[0,:])

[1.1 2.2 3.3]
[1.1 2.2 3.3]


In [35]:
# Indexing into all rows, second column
print(b[:,1])

[2.2 5.5]


In [37]:
# 0 in axis 0 gives first row, 1 in axis 1 gives second value
# Meanwhile, the second value in first list within array b also refers to 2.2
print(b[0,1])
print(b[0][1])

2.2
2.2


### Standard Mathematical Operations

In [39]:
np.random.seed(1) #initializes a random number generator

# let's create two 3x3 matrices filled with random integers in the range [0,10)
x = np.random.randint(0, 10, size = (3,3))
y = np.random.randint(0, 10, size = (3,3))

In [41]:
x

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [43]:
y

array([[9, 2, 4],
       [5, 2, 4],
       [2, 4, 7]])

In [45]:
x + y

array([[14, 10, 13],
       [10,  2,  4],
       [ 3, 11, 13]])

In [47]:
x - y

array([[-4,  6,  5],
       [ 0, -2, -4],
       [-1,  3, -1]])

In [49]:
x * y

array([[45, 16, 36],
       [25,  0,  0],
       [ 2, 28, 42]])

In [51]:
x / y  # division

array([[0.55555556, 4.        , 2.25      ],
       [1.        , 0.        , 0.        ],
       [0.5       , 1.75      , 0.85714286]])

In [53]:
x // y  # integer division (works like floor)

array([[0, 4, 2],
       [1, 0, 0],
       [0, 1, 0]])

In [55]:
x ** y  # raising x to the power of y

array([[1953125,      64,    6561],
       [   3125,       0,       0],
       [      1,    2401,  279936]])

In [57]:
print(np.sum(x))   # sum
print(np.mean(x))  # mean
print(np.std(x))   # standard deviation

41
4.555555555555555
3.235604395235786


In [59]:
# Will sum across the columns, outputting an array of the sums of each row.
print(np.sum(x, axis = 1))

[22  5 14]


In [61]:
# Will sum across the rows, outputting an array of the sums of each column.
print(np.sum(x, axis = 0))

[11 15 15]


In [63]:
# Same as normal sum because we sum across both axes
print(np.sum(x, axis = (0,1)))

41


### Other Numpy Features
* Transpose
* Magnitude (L2 norm)
* Dot Product
* Matrix Product
* Max/Min of an array

In [65]:
# We can easily get the transpose of a matrix (columns to rows, rows to columns)
print(x.T)

[[5 5 1]
 [8 0 7]
 [9 0 6]]


In [67]:
# Get the magnitude (L2 norm) of a vector
print(np.linalg.norm(x[0]))

13.038404810405298


In [69]:
# Get the dot product of two vectors
print(np.dot(x[0], x[1]))

25


In [71]:
# Multiply two matrices (m x k) * (k * n)
# Need same number of cols for first matrix and rows for second matrix
print(np.matmul(x, y))

[[103  62 115]
 [ 45  10  20]
 [ 56  40  74]]


In [75]:
# Minimum value in matrix
print(np.min(x))

# Minimum value in each row
print(np.min(x, axis = 1))

0
[5 0 1]


In [77]:
# Index of minimum value in matrix
print(np.argmin(x))

# Index of minimum value in each row
print(np.argmin(x, axis = 1))

4
[0 1 0]


## Adjusting Array Shape and Dimensionality
Sometimes our arrays are not in the specific format we want, so we need to restructure them. We can use `np.reshape()` to redistribute the existing array values into a different shape. The new shape must contain the same number of values as the original shape, but it can have a different number of dimensions.

In [79]:
y = np.arange(6)
print(y)

[0 1 2 3 4 5]


In [81]:
# Change the shape of y from (6,) to (2,3)
print(np.reshape(y, (2,3)))

[[0 1 2]
 [3 4 5]]


In [83]:
# If you list the size of one dimension as -1, NumPy will determine the appropriate value for you!
print(np.reshape(y, (-1, 2)))


[[0 1]
 [2 3]
 [4 5]]


In [85]:
y_new = np.reshape(y, (-1, 2))
y_new.shape

(3, 2)