### Imports
- If not already installed, don't forget to run `pip install numpy` and `pip install pandas` in your terminal first!  
- If that doesn't work, try `conda install numpy` and `conda install pandas` instead.

In [ ]:
# run this!
import pandas as pd
import numpy as np

### Creating Numpy Arrays

* NumPy arrays can be 1-dimensional, 2-dimensional (like a matrix), and so forth.   
* Each dimension is called an axis, and the `shape` property describes the array's size along each axis.  
* `a` only has 1 axis, and `b` and `c` have 2 axes.

In [ ]:
# Creating NumPy array from python list using np.array() function
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [ ]:
# These can be multiple dimensions -- just use nested lists!
b = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])  # 2x3 array
print(b)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [ ]:
c = np.array([[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]])  # 3x2 array
print(c)

[[1.1 2.2]
 [3.3 4.4]
 [5.5 6.6]]


In [ ]:
print([a.shape, b.shape, c.shape])
print([a.dtype, b.dtype, c.dtype])

[(6,), (2, 3), (3, 2)]
[dtype('int32'), dtype('float64'), dtype('float64')]
